version: '3'

services:
  backend:
    image: pelita_api_services
    build: .
    restart: unless-stopped
    ports:
      - "3003:3003"
    command: ["node", "index.js"]
    env_file:
      - .env
      - .env.development
    network_mode: "host"
  